name: Build-AppImage
run-name: Building AppImage
on:
  push:
    tags:
      - v**
jobs:
  Build-AppImage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo pip3 install appimage-builder
      - run: appimage-builder

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.AppImage"
          tags: true
          draft: false